Make pyflakes avoid viff.libs package.
We don't care about warnings to third-party libraries, and because of
pyflakes bug 1499 we get spurious warnings like this:

  viff/libs/configobj.py:40: redefinition of unused 'BOM_UTF8' from line 36
  viff/libs/configobj.py:42: redefinition of unused 'BOM_UTF16_LE' from line 36
  viff/libs/configobj.py:44: redefinition of unused 'BOM_UTF16_BE' from line 36
  viff/libs/configobj.py:47: redefinition of unused 'BOM_UTF16' from line 36

The pyflakes bug report:

  http://www.divmod.org/trac/ticket/1499